version: '3.6'

services:
    go-runtime:
        image: go-runtime
        build:
            context: .
        container_name: go-runtime
        hostname: go-runtime
        tty: true
        networks:
            - go-runtime

networks:
    go-runtime:
        driver: bridge
